#!/bin/bash
echo "Pulling Llama model..."
kamal accessory exec --reuse ollama ollama pull llama3.2
kamal accessory exec --reuse ollama ollama create custom-llama3.2 -f /ollama-config/Modelfile/Modelfile